Fix missing unistd.h include
```
/tmp/SZ/sz/src/rw.c:19:24: error: ‘F_OK’ undeclared (first use in this function)
  if( access( filePath, F_OK ) != -1 ) {
```